"""
Order Repository — MongoDB CRUD for orders collection.

All queries are org-scoped.  Uses the same patterns as other repositories
(find_one by id+org, find_by_org with filters, insert, update).

──────────────────────────────────────────────────────────────────────────
2026-05-20 — order_number CONTRACT (Golden Rule)
──────────────────────────────────────────────────────────────────────────
The canonical ``Order.order_number`` field follows ONE format, system-wide:

    ORD-{N:04d}     →     ORD-0001, ORD-0002, …, ORD-9999, ORD-10000

Rules:
  · Generated EXCLUSIVELY by ``get_next_order_number(org_id)`` below.
    No other code path should mint an order_number value.
  · ``N`` is a per-org monotonic counter (the unique partial index on
    ``(organization_id, order_number)`` guarantees uniqueness within
    an org; two different orgs can independently both have ORD-0001).
  · No store-scoped or year-scoped prefixes (``ORD-CB-XXXX``,
    ``ORD-2024-XXXX``, etc.) are part of the contract. A seed script
    that previously generated ``ORD-CB-XXXX`` was the only violation
    found in the codebase — it was rebranded to the canonical format
    on 2026-05-20 and a sentinel pins the invariant.

Importing legacy orders from external systems (Shopify, WooCommerce,
custom ERP, fatturazione elettronica, …)?
  · The IMPORTED system's identifier goes into a SEPARATE field
    ``external_order_number`` on the Order model. The order_number
    canonical stays ``ORD-XXXX`` and is generated by this function,
    untouched by import data.
  · ``external_source`` labels the origin (e.g. "shopify"). A non-
    unique compound index on (org, external_source,
    external_order_number) supports idempotent re-imports.

This separation keeps ``get_next_order_number`` simple and immune to
any future import format. Adding a new source is zero work on this
parser — only the import service learns about the new shape.
"""

import logging
import re
from typing import Optional, List

from database import orders_collection

logger = logging.getLogger(__name__)


# Regex that extracts the LAST run of digits in any string. Permissive
# against future drift: handles "ORD-0042", "ORD-CB-0162", "INV-2024-007",
# "1234". Returns None if there is no numeric tail at all. We accept the
# last digit-run rather than the first so the counter logic correctly
# advances past prefixes like year ("2024-007" → 7) or store_code
# ("CB-0162" → 162) without false-positives on accidental digits earlier
# in the string.
_ORDER_NUMBER_TAIL_DIGITS = re.compile(r"(\d+)\s*$")


async def insert(order_doc: dict) -> str:
    """Insert a single order document. Returns the order id."""
    await orders_collection.insert_one(order_doc)
    order_doc.pop("_id", None)  # remove MongoDB ObjectId (not JSON-serializable)
    return order_doc["id"]


async def find_one(order_id: str, org_id: str) -> Optional[dict]:
    """Find a single order by id within an org."""
    return await orders_collection.find_one(
        {"id": order_id, "organization_id": org_id},
        {"_id": 0},
    )


async def find_by_org(
    org_id: str,
    status: Optional[str] = None,
    limit: int = 200,
) -> List[dict]:
    """List orders for an org, optionally filtered by status."""
    query = {"organization_id": org_id}
    if status:
        query["status"] = status
    cursor = orders_collection.find(query, {"_id": 0}).sort("created_at", -1).limit(limit)
    return await cursor.to_list(length=limit)


async def update(order_id: str, org_id: str, updates: dict) -> bool:
    """Partial update of an order. Returns True if matched."""
    result = await orders_collection.update_one(
        {"id": order_id, "organization_id": org_id},
        {"$set": updates},
    )
    return result.matched_count > 0


async def get_next_order_number(org_id: str) -> str:
    """Generate the next canonical order number for an org.

    Returns a string in the canonical form ``ORD-{N:04d}`` (see module
    docstring for the contract). N is monotonic per-org.

    Algorithm (3 layers, fail-soft from top to bottom):

      1. PRIMARY — find the MAX of existing order_number in the org,
         extract its LAST run of digits via regex, increment.
         Handles every format the parser may encounter:
           "ORD-0042"        → 42  → next 43  → "ORD-0043"
           "ORD-CB-0162"     → 162 → next 163 → "ORD-0163"
           "ORD-2024-007"    → 7   → next 8   → "ORD-0008"
           "1234"            → 1234 → next 1235 → "ORD-1235"
         Note: when the MAX has a custom prefix, the next number drops
         that prefix and resumes the canonical form. The new value is
         still > all prior numeric tails for the org, so the unique
         partial index never collides.

      2. FALLBACK — if NO order_number on disk has any numeric tail
         (extreme edge: every legacy import is e.g. "ORD-NONE"), we
         take a COUNT of the existing assigned order_numbers and use
         count+1 as the seed. Worst case collides only if there's an
         exact ORD-{count+1:04d} already on disk — vanishingly rare
         and caught by the service-level retry loop.

      3. BOOTSTRAP — empty org (no assigned order_number at all) →
         "ORD-0001". The standard cold-start case.

    The function does NOT mutate any data. The actual assignment +
    collision-handling retry lives in ``services.order_service
    .confirm_order``.

    Race-safety: not perfect under concurrent confirms, but the unique
    partial index ``(org_id, order_number)`` guarantees no duplicates,
    and the service retry loop converges on the next available number
    in at most 1-2 retries even under contention.
    """
    cursor = orders_collection.find(
        {"organization_id": org_id, "order_number": {"$ne": None}},
        {"_id": 0, "order_number": 1},
    ).sort("order_number", -1).limit(1)
    docs = await cursor.to_list(length=1)

    # Layer 3: bootstrap — empty org.
    if not docs:
        return "ORD-0001"

    # Layer 1: extract the last digit-run from the MAX.
    last = docs[0].get("order_number") or ""
    m = _ORDER_NUMBER_TAIL_DIGITS.search(last)
    if m:
        try:
            num = int(m.group(1)) + 1
            return f"ORD-{num:04d}"
        except (ValueError, OverflowError):
            # Extremely unlikely (regex matched digits) but guard anyway.
            logger.warning(
                "order_repository.get_next_order_number: regex matched "
                "but int() failed on order_number=%r org=%s — falling "
                "back to count-based",
                last, org_id,
            )

    # Layer 2: count-based fallback. The MAX has no digit tail at all
    # (e.g. someone imported orders with order_number="UNDEFINED").
    # We're not crashing — but we log loudly so ops sees this org has
    # malformed data on disk that should be cleaned up.
    logger.warning(
        "order_repository.get_next_order_number: MAX order_number=%r "
        "has no numeric tail for org=%s — using count-based fallback. "
        "This is a signal that the org has imported orders with non-"
        "standard order_number format; consider running a rebrand "
        "migration to canonical ORD-XXXX shape.",
        last, org_id,
    )
    count = await orders_collection.count_documents(
        {"organization_id": org_id, "order_number": {"$ne": None}},
    )
    return f"ORD-{count + 1:04d}"
