"""
AI Insight Service — module-agnostic orchestrator (DEPRECATED).

Wave 8A.0 (2026-05): this service is DEAD CODE. The /insights endpoint
returns 410 Gone (see routers/insights.py) and no code path in the
active backend calls generate_cashflow_insight() any more.

The file is kept because:
  1. Removing it would require touching multiple imports just to delete
     unused symbols, increasing the blast radius of Wave 8A.0.
  2. If we ever decide to revive insights, the structure here is still
     valid — we'd just need to wire record_usage() at line ~95 and add
     org_id/user_id propagation.

Until then, the public entry point is guarded: calling
generate_cashflow_insight() logs a loud warning so any silent
revival is immediately visible in logs (and grep-able).

Dispatches insight generation to the appropriate module's insight_builder
via core.module_registry.  The cashflow-specific content (system prompt,
user message, fallback text, data enrichment) lives in
modules/cashflow_monitor/insight_builder.py.
"""
import logging
from typing import Optional

from models import Insight
from services.ai_analytics_service import _get_date_range
from services.claude_client import (
    send_message_with_usage, ClaudeUnavailableError, is_available,
    get_active_model, calculate_cost_usd,
)
from repositories.usage_repository import record_usage

logger = logging.getLogger(__name__)

# Wave 8A.0 — sentinel: if this counter increases in production logs we
# know the dead code was re-activated and we should harden the path.
_DEPRECATED_INVOCATION_WARN_INTERVAL = 1  # log every call, this is suspicious

_SCHEMA_VERSION = "2.0"
_MODEL_TAG = "claude-sonnet"


async def generate_cashflow_insight(
    org_id: str,
    period: str = "30d",
    start_date: Optional[str] = None,
    end_date: Optional[str] = None,
    force: bool = False,
    *,
    user_id: Optional[str] = None,
) -> Optional[Insight]:
    """Generate an AI insight for cashflow analysis and return an Insight object.

    DEPRECATED (Wave 8A.0): no active code path calls this. If you're
    looking at this function and considering using it, talk to the AI
    governance owner first — there's almost certainly a better path
    (digest_builder for periodic summaries, query_business_summary
    tool for on-demand insights via chat).

    Wave 8A.0: ``user_id`` accepted (keyword-only) so any revival path
    can attribute the usage properly. AIUsageEvent will be recorded
    automatically on every successful Anthropic call here.

    Optimization: if the latest insight covers the same period and was
    generated by Claude (not fallback), returns the existing one to avoid
    a redundant API call.  Pass force=True to skip this check.

    Returns None when:
    - The module is not registered or has no insight_builder.
    - The builder returns None (no data for the period).
    """
    logger.warning(
        "ai_insight_service.generate_cashflow_insight called (DEAD CODE in Wave 8A.0). "
        "org_id=%s period=%s — verify this is intentional.",
        org_id, period,
    )
    from core.module_registry import get as registry_get
    from repositories import insight_repository

    start, end = _get_date_range(period, start_date, end_date)

    # ── Reuse check: skip Claude call if latest insight matches period ────
    if not force:
        latest_doc = await insight_repository.find_latest(org_id, "cashflow_monitor")
        if (
            latest_doc
            and latest_doc.get("period_start") == start
            and latest_doc.get("period_end") == end
            and latest_doc.get("model_version") == _MODEL_TAG
        ):
            logger.info("ai_insight_service: reusing existing insight for %s [%s→%s]", org_id, start, end)
            return insight_repository.doc_to_insight(latest_doc)

    module = registry_get("cashflow_monitor")
    if module is None or module.insight_builder is None:
        logger.warning(
            "ai_insight_service: no insight_builder registered for cashflow_monitor"
        )
        return None

    context = await module.insight_builder(org_id, start, end)
    if context is None:
        return None

    try:
        if not is_available():
            raise ClaudeUnavailableError("Claude API not configured")

        content, usage = await send_message_with_usage(
            system=context["system_prompt"],
            user_message=context["user_message"],
            max_tokens=2048,
        )
        used_model = _MODEL_TAG

        # Wave 8A.0 — record the AIUsageEvent. If this function is ever
        # re-activated, every Anthropic invocation is tracked. agent_id
        # makes it grep-able if it shows up in the governance dashboard.
        model_version = get_active_model()
        cost = calculate_cost_usd(
            tokens_prompt=usage.get("input_tokens"),
            tokens_completion=usage.get("output_tokens"),
            cache_read_tokens=usage.get("cache_read_tokens", 0),
            cache_creation_tokens=usage.get("cache_creation_tokens", 0),
            model_version=model_version,
        )
        try:
            await record_usage(
                org_id=org_id,
                module_key="ai_assistant",
                feature_key="insight",
                quantity=1,
                tokens_prompt=usage.get("input_tokens"),
                tokens_completion=usage.get("output_tokens"),
                cache_read_tokens=usage.get("cache_read_tokens"),
                cache_creation_tokens=usage.get("cache_creation_tokens"),
                provider="anthropic",
                model_version=model_version,
                cost_usd=cost,
                user_id=user_id,
                agent_id="ai_insight_service",
            )
        except Exception as track_exc:
            logger.warning(
                "ai_insight_service: record_usage failed for org=%s: %s",
                org_id, track_exc,
            )

    except (ClaudeUnavailableError, Exception) as e:
        logger.warning("AI insight generation error: %s", str(e))
        content = context["fallback_content"]
        used_model = "fallback"

    return Insight(
        organization_id=org_id,
        module_key=context["module_key"],
        title=context["title"],
        content=content,
        metrics_context=context["metrics_context"],
        period_start=start,
        period_end=end,
        schema_version=_SCHEMA_VERSION,
        model_version=used_model,
    )
