"""
digital_storage.py — secure filesystem layer for downloadable digital products.

Release 3 (Digital) B2.

The rest of the platform uses `backend/uploads/` which is served publicly via
a FastAPI StaticFiles mount (`/uploads/*` → anonymous GET). That is fine for
images but absolutely wrong for paid digital goods: anyone who guesses or
leaks a URL would download the file.

This module writes digital payloads to a SEPARATE root
(`backend/private_uploads/digital/`) that is NEVER mounted as StaticFiles.
The only way to read those files is through the token-gated endpoint at
`/public/downloads/{access_token}/file` (Release 3 B5) which:
  - verifies the IssuedDownload token is still active
  - increments a download counter atomically
  - streams the file with FileResponse + Content-Disposition

API:
    save_digital_file(org_id, product_id, upload_file) -> dict
        Persist the uploaded bytes and return a snapshot dict with
        `filename`, `size_bytes`, `mime_type` suitable to be stored on the
        product's metadata (DigitalMetadata).

    resolve_digital_path(org_id, product_id) -> Path
        Return the absolute on-disk path of the currently stored file for
        `(org_id, product_id)`. Raises FileNotFoundError when nothing is
        stored. Path-traversal safe: both arguments are sanitized and the
        result is guaranteed to live under the private root.

    delete_digital_file(org_id, product_id) -> bool
        Remove the stored file (and its per-product directory) if present.
        Idempotent: returns False when nothing existed.

Constraints:
  * Max upload size: 100 MB (configurable via DIGITAL_MAX_UPLOAD_BYTES env).
  * Extension derived from original filename; no server-side MIME sniffing.
  * One file per (org_id, product_id). A new upload REPLACES the prior file
    (previous bytes are deleted to avoid orphaned payloads).
"""

from __future__ import annotations

import logging
import os
import re
import shutil
import uuid
from pathlib import Path
from typing import Dict, Optional

from fastapi import UploadFile


logger = logging.getLogger(__name__)


# ── Constants ──────────────────────────────────────────────────────────────

# Separate root — not under `backend/uploads/` so the StaticFiles mount
# cannot expose files here. Absolute path resolved at import time so
# subsequent operations are cheap.
_THIS_DIR = Path(__file__).resolve().parent
_BACKEND_DIR = _THIS_DIR.parent
_PRIVATE_ROOT = _BACKEND_DIR / "private_uploads" / "digital"

# Upload ceiling — large enough for typical PDFs / audio / small archives
# without DoS'ing the server. Overridable via env for orgs with bigger needs.
_MAX_UPLOAD_BYTES = int(os.environ.get("DIGITAL_MAX_UPLOAD_BYTES", 100 * 1024 * 1024))

# Filenames allowed on disk — generated by us, so the pattern is strict.
# `{uuid}.{ext}` where ext is ASCII alphanumeric.
_SAFE_ID = re.compile(r"^[a-zA-Z0-9_\-]+$")


# ── Internal helpers ───────────────────────────────────────────────────────


def _safe_segment(value: str, *, field: str) -> str:
    """Reject any path segment that could cause traversal.

    Accepts only alphanumerics, dashes and underscores. This matches what
    generate_id() emits; any user input (e.g. a legacy / imported id) that
    doesn't fit is rejected loudly rather than silently coerced.
    """
    if not value or not _SAFE_ID.match(value):
        raise ValueError(f"digital_storage: invalid {field}: {value!r}")
    return value


def _product_dir(org_id: str, product_id: str) -> Path:
    """Return the absolute directory under the private root for this pair."""
    safe_org = _safe_segment(org_id, field="org_id")
    safe_prod = _safe_segment(product_id, field="product_id")
    return _PRIVATE_ROOT / safe_org / safe_prod


def _extension_from_filename(filename: Optional[str]) -> str:
    """Derive a safe extension. Unknown / missing → empty string."""
    if not filename:
        return ""
    base = os.path.basename(filename)
    dot = base.rfind(".")
    if dot < 0:
        return ""
    ext = base[dot + 1:].lower()
    # Strip anything non-ascii-alphanumeric to avoid `..`-style paths.
    ext = re.sub(r"[^a-z0-9]", "", ext)
    # Cap length so a pathological 200-char extension can't occur.
    return ext[:10]


# ── Public API ─────────────────────────────────────────────────────────────


async def save_digital_file(
    org_id: str,
    product_id: str,
    upload_file: UploadFile,
) -> Dict[str, object]:
    """Persist the uploaded file and return its snapshot metadata.

    Replaces any previously stored file for (org_id, product_id). The
    caller is expected to then update `product.metadata` with the returned
    filename / size / mime so reads can surface them to the storefront.
    """
    target_dir = _product_dir(org_id, product_id)
    # Clear any pre-existing files so only one payload per product lives on
    # disk. Atomicity is not critical here — the product.metadata is the
    # source of truth, and a stale orphan is harmless (served only through
    # the token endpoint which uses metadata.download_filename).
    if target_dir.exists():
        for entry in target_dir.iterdir():
            try:
                if entry.is_file():
                    entry.unlink()
            except OSError:
                # Best-effort cleanup; keep going.
                logger.warning("digital_storage: could not remove stale file %s", entry)
    target_dir.mkdir(parents=True, exist_ok=True)

    # Write streaming to disk while tracking size. Reject early when we
    # cross _MAX_UPLOAD_BYTES without touching the caller's memory.
    ext = _extension_from_filename(upload_file.filename)
    stored_name = f"{uuid.uuid4().hex}{('.' + ext) if ext else ''}"
    file_path = target_dir / stored_name

    size = 0
    chunk_size = 1024 * 1024  # 1 MB chunks
    try:
        with file_path.open("wb") as fh:
            while True:
                chunk = await upload_file.read(chunk_size)
                if not chunk:
                    break
                size += len(chunk)
                if size > _MAX_UPLOAD_BYTES:
                    fh.close()
                    try:
                        file_path.unlink()
                    except OSError:
                        pass
                    raise ValueError(
                        f"Il file supera la dimensione massima consentita "
                        f"({_MAX_UPLOAD_BYTES // (1024 * 1024)} MB)."
                    )
                fh.write(chunk)
    except ValueError:
        # Propagate size-limit exception unchanged so the router maps it to 413.
        raise
    except Exception as exc:
        logger.exception("digital_storage: write failed for %s/%s: %s", org_id, product_id, exc)
        try:
            file_path.unlink()
        except OSError:
            pass
        raise

    # Snapshot returned to the caller — these end up in metadata.
    # The original filename is surfaced to the customer; the on-disk name
    # (UUID-based) is an implementation detail and intentionally NOT returned.
    original_name = (upload_file.filename or stored_name).strip() or stored_name
    mime = (upload_file.content_type or "application/octet-stream").split(";", 1)[0].strip()
    return {
        "filename": original_name[:255],
        "size_bytes": size,
        "mime_type": mime[:120],
    }


def resolve_digital_path(org_id: str, product_id: str) -> Path:
    """Return the absolute path of the currently stored file.

    Raises FileNotFoundError when no file exists. The returned path is
    ALWAYS under `_PRIVATE_ROOT` by construction (segments are sanitized),
    so callers can trust it for FileResponse without additional checks.
    """
    target_dir = _product_dir(org_id, product_id)
    if not target_dir.exists() or not target_dir.is_dir():
        raise FileNotFoundError(f"No digital payload for {org_id}/{product_id}")
    # One file per directory by convention; return the first regular file.
    for entry in sorted(target_dir.iterdir()):
        if entry.is_file():
            resolved = entry.resolve()
            # Defense in depth: verify the resolved path still sits under the
            # private root. Should always be true given the sanitized
            # segments above; this guards against symlink shenanigans.
            try:
                resolved.relative_to(_PRIVATE_ROOT.resolve())
            except ValueError as exc:
                raise FileNotFoundError(
                    f"Resolved path escapes private root: {resolved}"
                ) from exc
            return resolved
    raise FileNotFoundError(f"Directory exists but empty: {target_dir}")


def delete_digital_file(org_id: str, product_id: str) -> bool:
    """Remove the stored file (and its directory). Idempotent."""
    try:
        target_dir = _product_dir(org_id, product_id)
    except ValueError:
        return False
    if not target_dir.exists():
        return False
    try:
        shutil.rmtree(target_dir)
        return True
    except OSError as exc:
        logger.warning("digital_storage: delete failed for %s/%s: %s", org_id, product_id, exc)
        return False


def max_upload_bytes() -> int:
    """Expose the configured ceiling so the router can surface it in errors."""
    return _MAX_UPLOAD_BYTES
