"""
Module Registry — core infrastructure.

Central registry for all AFianco modules.  Each module registers
itself at import time by calling register() with a ModuleDefinition.

Design principles:
  - Pure Python: no imports from the application layer (leaf node, no
    circular-import risk from any direction).
  - Explicit registration: modules call register() in their __init__.py;
    no filesystem auto-discovery here (that lives in modules/__init__.py
    for UI metadata).
  - Idempotent: calling register() twice for the same key overwrites
    silently — safe for reload scenarios.
  - Minimal: capabilities are added on demand as Optional[Callable] fields;
    a module omits a capability by leaving the field at its None default.
"""
from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import Callable, List, Optional

logger = logging.getLogger(__name__)


# ── Module descriptor ─────────────────────────────────────────────────────────

@dataclass
class ModuleDefinition:
    """Capabilities and metadata for a registered module.

    Required fields:
        module_key   – unique slug, e.g. "cashflow_monitor"
        module_name  – human-readable label

    Optional capabilities (None = not supported by this module):
        snapshot_builder
            async callable(org_id: str, start_date: str, end_date: str) -> dict
            Returns the metrics dict to persist in kpi_snapshots.

        post_upload_hooks
            List of async callables(org_id: str) -> None.
            Fired fire-and-forget after every successful dataset upload.
            Each hook must handle its own errors; a failure in one does
            not prevent others from running.

        alert_rules
            async callable(org_id: str) -> List[Alert]
            Returns the list of new Alert objects to persist.  The function
            is responsible for its own data loading and deduplication logic.
            alert_service dispatches to this and calls create_many() on result.

        insight_builder
            async callable(org_id: str, start: str, end: str) -> Optional[dict]
            Returns a context dict consumed by ai_insight_service to drive
            the LLM call.  Keys: system_prompt, user_message, fallback_content,
            module_key, title, metrics_context.  Returns None if no data.

        overview_builder
            async callable(org_id: str, period: str, start_date: Optional[str],
                           end_date: Optional[str], **kwargs) -> Optional[dict]
            Returns the composite overview dict for the module page.  Runs
            all data queries in parallel and assembles KPIs, chart series,
            categories, open alerts, and the last insight into a single
            response.  Returns None when there is no data for the period.
            Consumed by GET /api/modules/{module_key}/overview.
            Receives locale=<str> via kwargs for AI-generating modules.

        digest_builder
            async callable(org_id: str, period_days: int, digest_type: str) -> Optional[dict]
            Generates a periodic digest (weekly/monthly) for the module.
            Returns a dict ready to be saved as a Digest model, or None
            if no data is available.  Falls back to rule-based content
            when the LLM is unavailable.

        alert_analysis
            async callable(alerts: list, kpis: dict, locale: str = "it") -> dict[str, str]
            Batch AI root-cause analysis for alerts generated by this module.
            Returns {alert_id: analysis_text}.  Never raises.
            locale controls the AI response language.

        health_explanation_ai
            async callable(health_score: dict, kpis: dict, locale: str = "it") -> str
            AI-powered explanation of the module's health score.
            Falls back to rule-based explanation on error.  Never raises.
            locale controls the AI response language.

        ai_tool_definitions
            List[Dict[str, Any]]
            Provider-agnostic tool definitions for the AI chat assistant.
            Each dict has keys: name, description, parameters, required.
            Provider-specific conversion (e.g. to Anthropic format) is
            performed by the platform's ai_tool_registry, not by the module.

        ai_tool_executor
            async callable(org_id: str, tool_name: str, tool_input: dict) -> dict
            Executes one of the module's AI tools.  Receives the org_id for
            data scoping, the tool name matching one of ai_tool_definitions,
            and the tool input dict.  Returns a JSON-serializable result dict.
    """
    module_key: str
    module_name: str
    is_available: bool = True
    # ── UI metadata (rendered on the merchant /modules page) ──────────────────
    # These three fields used to live in the legacy ``modules/<x>/config.py``
    # files consumed by ``ModuleRegistry.discover_modules()`` (filesystem scan).
    # They now live here so a single ``register()`` call is the only place a
    # module needs to declare itself. Defaults are safe placeholders so older
    # call sites that omit them keep working.
    description: str = ""
    category: str = "other"
    icon: str = "activity"
    snapshot_builder: Optional[Callable] = None
    post_upload_hooks: List[Callable] = field(default_factory=list)
    alert_rules: Optional[Callable] = None
    insight_builder: Optional[Callable] = None
    overview_builder: Optional[Callable] = None
    digest_builder: Optional[Callable] = None
    alert_analysis: Optional[Callable] = None
    health_explanation_ai: Optional[Callable] = None
    ai_tool_definitions: Optional[list] = None
    ai_tool_executor: Optional[Callable] = None


# ── Registry storage ──────────────────────────────────────────────────────────

_registry: dict[str, ModuleDefinition] = {}


def register(module: ModuleDefinition) -> None:
    """Register a module.  Idempotent: re-registering the same key overwrites."""
    _registry[module.module_key] = module
    logger.debug("module_registry: registered module_key=%s", module.module_key)


def get(module_key: str) -> Optional[ModuleDefinition]:
    """Return the ModuleDefinition for the given key, or None if not registered."""
    return _registry.get(module_key)


def get_all() -> List[ModuleDefinition]:
    """Return all registered modules (insertion order preserved, Python 3.7+)."""
    return list(_registry.values())


def get_all_for_ui() -> List[dict]:
    """UI-shaped projection of registered modules.

    Returns dicts with keys ``key, name, description, category, icon,
    is_available`` — the exact shape produced by the legacy
    ``modules.get_registered_modules()``.  Consumed by
    ``routers/modules.py::get_all_modules`` and
    ``routers/admin.py::_all_known_module_keys``.

    Kept separate from ``get_all()`` (which returns ModuleDefinition
    objects with full capabilities) so the consolidation from the
    legacy filesystem-scanning registry is an explicit, testable
    1-to-1 shape swap.
    """
    return [
        {
            "key": m.module_key,
            "name": m.module_name,
            "description": m.description,
            "category": m.category,
            "icon": m.icon,
            "is_available": m.is_available,
        }
        for m in get_all()
    ]
