"""
EventOccurrence — a dated instance of an event_ticket product.

Example:
  Product: "Cena in Masseria" (item_type=event_ticket)
  Occurrence A: 2026-08-14 at 20:30, capacity 40
  Occurrence B: 2026-08-21 at 20:30, capacity 40

Occurrences are org-scoped and linked to a product via product_id.
Only products with item_type="event_ticket" may have occurrences.

E2 — structured event details:
  The pre-E2 schema carried only a single `location` text (max 255) and
  terse `notes`. E2 adds structured fields so the storefront can render
  a proper event page (venue + address + map pin + hero image + long
  description in markdown). EVERY new field is optional — a pre-E2
  occurrence continues to serialize and display correctly; the public
  catalog falls back to `location` text when structured fields are
  absent.
"""

from pydantic import BaseModel, Field, ConfigDict, field_validator
from typing import Optional
from datetime import datetime
from .common import generate_id, utc_now

OCCURRENCE_STATUSES = ("draft", "published", "closed", "cancelled")


class EventOccurrenceBase(BaseModel):
    product_id: str                                # FK → products._id (must be event_ticket)
    start_at: str                                  # ISO datetime: "2026-08-14T20:30:00"
    end_at: Optional[str] = None                   # ISO datetime (optional)
    location: Optional[str] = Field(default=None, max_length=255)
    capacity: Optional[int] = Field(default=None, ge=1)
    price_override: Optional[float] = Field(default=None, ge=0)  # overrides product.unit_price
    notes: Optional[str] = Field(default=None, max_length=1000)

    # ── E2: structured location ──────────────────────────────────────────
    # All optional. When the admin fills them, the storefront renders a
    # proper venue card + map link. `location` text remains a free-form
    # fallback (e.g. "Online event — link inviato dopo l'acquisto").
    venue_name: Optional[str] = Field(default=None, max_length=150)
    address: Optional[str] = Field(default=None, max_length=255)
    city: Optional[str] = Field(default=None, max_length=100)
    postal_code: Optional[str] = Field(default=None, max_length=20)
    country: Optional[str] = Field(default=None, max_length=2)  # ISO-3166 alpha-2
    latitude: Optional[float] = Field(default=None, ge=-90, le=90)
    longitude: Optional[float] = Field(default=None, ge=-180, le=180)
    # Optional explicit map URL override. When absent, the storefront
    # builds a link from lat/lng or from the full address (see helper
    # `build_map_url`). Never geocoded server-side — manual paste only.
    map_url: Optional[str] = Field(default=None, max_length=500)

    # ── E2: presentation ─────────────────────────────────────────────────
    # Hero image for the landing page (E3). Square / wide ratios both
    # supported by the frontend; full URL or relative to /uploads.
    cover_image_url: Optional[str] = Field(default=None, max_length=500)
    # Long markdown description. Renders on the landing page. Keep under
    # 5000 chars — Michele writes the story of the evening, not a novel.
    long_description: Optional[str] = Field(default=None, max_length=5000)
    # Optional external reference (EventBrite id, Ticketone code, ecc.)
    # purely informative — never dereferenced server-side.
    external_ref_id: Optional[str] = Field(default=None, max_length=100)

    # E3: URL slug for the public landing page. Optional — autogenerated
    # at create time from product name + date when missing. Enforced
    # unique per organization by a sparse index in database.py. Admin
    # can override manually from the occurrence editor.
    slug: Optional[str] = Field(default=None, max_length=160)

    # G6: archive flag. Archived events disappear from the default
    # /events listing so the admin isn't cluttered by past editions,
    # but remain reachable via the "Archivio" filter and by direct URL.
    # Never set automatically — the merchant chooses to archive.
    is_archived: bool = False

    @field_validator("country", mode="before")
    @classmethod
    def _normalize_country(cls, v):
        """Accept either uppercase or lowercase; store uppercase ISO-2."""
        if v is None or v == "":
            return None
        if not isinstance(v, str):
            return v
        code = v.strip().upper()
        return code or None


class EventOccurrenceCreate(EventOccurrenceBase):
    pass


class EventOccurrenceUpdate(BaseModel):
    model_config = ConfigDict(extra="ignore")

    start_at: Optional[str] = None
    end_at: Optional[str] = None
    location: Optional[str] = None
    capacity: Optional[int] = None
    price_override: Optional[float] = None
    notes: Optional[str] = None
    status: Optional[str] = None
    # E2 additions
    venue_name: Optional[str] = Field(default=None, max_length=150)
    address: Optional[str] = Field(default=None, max_length=255)
    city: Optional[str] = Field(default=None, max_length=100)
    postal_code: Optional[str] = Field(default=None, max_length=20)
    country: Optional[str] = Field(default=None, max_length=2)
    latitude: Optional[float] = Field(default=None, ge=-90, le=90)
    longitude: Optional[float] = Field(default=None, ge=-180, le=180)
    map_url: Optional[str] = Field(default=None, max_length=500)
    cover_image_url: Optional[str] = Field(default=None, max_length=500)
    long_description: Optional[str] = Field(default=None, max_length=5000)
    external_ref_id: Optional[str] = Field(default=None, max_length=100)
    slug: Optional[str] = Field(default=None, max_length=160)
    is_archived: Optional[bool] = None   # G6 — admin toggle

    @field_validator("country", mode="before")
    @classmethod
    def _normalize_country_update(cls, v):
        if v is None or v == "":
            return None
        if not isinstance(v, str):
            return v
        code = v.strip().upper()
        return code or None


class EventOccurrence(EventOccurrenceBase):
    model_config = ConfigDict(extra="ignore")

    id: str = Field(default_factory=generate_id)
    organization_id: str
    status: str = "draft"                          # draft | published | closed | cancelled
    created_at: datetime = Field(default_factory=utc_now)
    updated_at: datetime = Field(default_factory=utc_now)


class EventOccurrenceResponse(EventOccurrenceBase):
    id: str
    organization_id: str
    status: str
    product_name: Optional[str] = None             # denormalized for display
    created_at: datetime
    updated_at: datetime


def slugify(value: Optional[str]) -> str:
    """Conservative URL-safe slugifier.

    Lowercases, replaces any run of non-alphanum with "-", strips
    leading/trailing dashes. ASCII-only to keep URLs clean even for
    non-latin sources. Truncates at 80 chars.

    Returns "" when the input is falsy after normalization — the caller
    decides whether that's acceptable (we fall back to the occurrence
    date).
    """
    import re
    import unicodedata

    if not value:
        return ""
    # NFKD decompose + strip combining marks -> plain ASCII where possible
    normalized = unicodedata.normalize("NFKD", str(value))
    ascii_only = "".join(ch for ch in normalized if not unicodedata.combining(ch))
    lowered = ascii_only.lower()
    # Replace anything non-alphanum with "-"
    dashed = re.sub(r"[^a-z0-9]+", "-", lowered)
    # Collapse repeated dashes and strip
    clean = dashed.strip("-")
    return clean[:80]


async def generate_occurrence_slug(
    *,
    org_id: str,
    product_name: Optional[str],
    start_at: Optional[str],
    exclude_id: Optional[str] = None,
) -> str:
    """Build a unique slug for an occurrence, handling collisions.

    Composition: `slugify(product_name)-YYYY-MM-DD`. When the product
    name is empty the date alone is used. When two occurrences would
    collide (same product, same day), a short numeric suffix is appended
    (`-2`, `-3`, …) until the slug is free within the organization.

    `exclude_id` is respected during updates so an occurrence does not
    collide with itself.
    """
    base_name = slugify(product_name) if product_name else ""

    date_part = ""
    if start_at:
        try:
            # Accept ISO datetimes "2026-08-14T20:00:00" — keep the date.
            date_part = start_at[:10]
            # Light validation: must look like YYYY-MM-DD
            import re
            if not re.fullmatch(r"\d{4}-\d{2}-\d{2}", date_part):
                date_part = ""
        except Exception:
            date_part = ""

    parts = [p for p in (base_name, date_part) if p]
    base = "-".join(parts) or "evento"

    from database import event_occurrences_collection

    # Try the base first, then append -2, -3, … on collision.
    candidate = base
    suffix = 1
    while True:
        query = {"organization_id": org_id, "slug": candidate}
        if exclude_id:
            query["id"] = {"$ne": exclude_id}
        taken = await event_occurrences_collection.find_one(query, {"_id": 0, "id": 1})
        if not taken:
            return candidate
        suffix += 1
        candidate = f"{base}-{suffix}"
        if suffix > 50:  # defensive upper bound — should never hit in practice
            import secrets
            return f"{base}-{secrets.token_hex(3)}"


def build_map_url(occ: dict) -> Optional[str]:
    """Derive a Google Maps URL from an occurrence's location fields.

    Precedence:
      1. Explicit `map_url` field (admin override).
      2. lat/lng pair if both set.
      3. Composed address (venue + address + city + postal + country).
      4. Legacy `location` text.
      5. None — storefront omits the map link.

    The function is read-only; it never geocodes. Kept out of the
    Pydantic model to keep the schema side-effect free (dict in, str
    or None out). Called by the public catalog and the landing page
    endpoints when rendering event cards.
    """
    if not occ:
        return None

    explicit = occ.get("map_url")
    if explicit:
        return explicit

    lat, lng = occ.get("latitude"), occ.get("longitude")
    if lat is not None and lng is not None:
        return f"https://www.google.com/maps/search/?api=1&query={lat},{lng}"

    parts = [
        occ.get("venue_name"),
        occ.get("address"),
        occ.get("postal_code"),
        occ.get("city"),
        occ.get("country"),
    ]
    composed = ", ".join(str(p) for p in parts if p)
    if composed:
        from urllib.parse import quote_plus
        return f"https://www.google.com/maps/search/?api=1&query={quote_plus(composed)}"

    legacy = occ.get("location")
    if legacy:
        from urllib.parse import quote_plus
        return f"https://www.google.com/maps/search/?api=1&query={quote_plus(legacy)}"

    return None
