"""
Alert AI Analysis — batch root-cause analysis for cashflow alerts.

Takes a list of Alert objects and sends a single Claude call to generate
a root-cause analysis + suggested action for each alert.

Public interface:
    analyze_alerts(alerts, kpis, locale) -> dict[str, str]
        Returns {alert_id: analysis_text}. Never raises.
"""
import logging
from typing import List, Dict, Optional

logger = logging.getLogger(__name__)


def _build_system_prompt(locale: str = "it") -> str:
    """Build locale-aware system prompt for alert analysis."""
    from core.locale_utils import get_locale_profile
    profile = get_locale_profile(locale)
    return (
        "You are a financial advisor for SMEs. "
        "You are presented with financial alerts generated by the monitoring system. "
        "For each alert:\n"
        "1. Identify the probable root cause based on the data\n"
        "2. Suggest a concrete and specific action\n"
        f"{profile.respond_instruction}. "
        "For each alert use the exact format:\n"
        "[ALERT_ID] 2-3 sentences with cause and action.\n"
        "Be specific, practical, and concise. "
        "IMPORTANT: 'Giorni autonomia' is estimated from burn rate, NOT actual bank balance — qualify it. "
        "DSO/DPO may be unreliable if payment_status/due_date fields are missing — note when both are 0. "
        f"When citing numbers, use {profile.number_format_hint}."
    )


def _build_batch_message(alerts: list, kpis: dict) -> str:
    alert_lines = []
    for a in alerts:
        severity = a.severity.value.upper() if hasattr(a.severity, 'value') else str(a.severity).upper()
        alert_lines.append(f"[{a.id}] {severity} — {a.title}: {a.summary}")

    kpi_context = (
        f"Contesto KPI:\n"
        f"- Ricavi: {kpis.get('total_sales', 0):,.0f} EUR\n"
        f"- Uscite totali: {kpis.get('total_outflows', 0):,.0f} EUR\n"
        f"- Margine operativo: {kpis.get('operating_margin_pct', 0):.1f}%\n"
        f"- DSO: {kpis.get('dso', 0):.0f} giorni\n"
        f"- DPO: {kpis.get('dpo', 0):.0f} giorni\n"
        f"- Giorni autonomia: {kpis.get('giorni_autonomia', 0):.0f}\n"
        f"- Rapporto uscite: {kpis.get('total_outflow_ratio', 0):.1f}%"
    )

    return (
        f"{kpi_context}\n\n"
        f"Alert da analizzare:\n"
        f"{chr(10).join(alert_lines)}\n\n"
        f"Per ciascun alert, fornisci causa radice e azione suggerita."
    )


def _parse_response(response: str, alert_ids: List[str]) -> Dict[str, str]:
    """Parse batched response into per-alert analyses."""
    result = {}
    current_id = None
    current_lines = []

    for line in response.split("\n"):
        matched_id = None
        for aid in alert_ids:
            if f"[{aid}]" in line:
                matched_id = aid
                break

        if matched_id:
            if current_id and current_lines:
                result[current_id] = " ".join(current_lines).strip()
            current_id = matched_id
            current_lines = [line.split("]", 1)[-1].strip()]
        elif current_id and line.strip():
            current_lines.append(line.strip())

    if current_id and current_lines:
        result[current_id] = " ".join(current_lines).strip()

    return result


_ALERT_BATCH_MAX = 20  # Wave 9.C.2: cap per-call to keep tokens predictable


async def analyze_alerts(
    alerts: list, kpis: dict, locale: str = "it",
    *,
    organization_id: Optional[str] = None,
) -> Dict[str, str]:
    """Batch-analyze alerts via Claude. Returns {alert_id: analysis}.
    Never raises.

    Wave 9.B (2026-05): two improvements landed together:
      1. Tracking gap closed — every call now writes an AIUsageEvent
         (feature='alert_analysis') with tokens + cost_usd. Before
         this, alert AI analysis was invisible to the governance
         dashboard. Pass ``organization_id`` for proper attribution.
      2. Haiku 4 instead of Sonnet — alert analysis is short-form
         summarization, doesn't need Sonnet's reasoning. Saves ~75%
         per call. Falls back to provider default via
         resolve_non_chat_model() when ops set LLM_NON_CHAT_MODEL=default.

    Wave 9.C.2 (2026-05): batch size cap. If the alert engine fires
    100 alerts in one tick (e.g. a missing-data day produces alerts
    for every category), we now do 5 calls of 20 instead of 1 mega-call
    of 100. Bounds the worst-case token usage per Anthropic round-trip
    to a predictable ceiling, eliminates the long single-call latency
    spike, and lets the kill switch / budget guards cut us off mid-loop.
    """
    if not alerts:
        return {}

    # Wave 9.C.2 — recursively split when over the cap. Each sub-batch
    # is a normal call → tracking + Haiku + governance all apply per batch.
    if len(alerts) > _ALERT_BATCH_MAX:
        logger.info(
            "alert_analysis: splitting %d alerts into batches of %d",
            len(alerts), _ALERT_BATCH_MAX,
        )
        combined: Dict[str, str] = {}
        for i in range(0, len(alerts), _ALERT_BATCH_MAX):
            sub_batch = alerts[i:i + _ALERT_BATCH_MAX]
            sub_result = await analyze_alerts(
                sub_batch, kpis, locale,
                organization_id=organization_id,
            )
            combined.update(sub_result)
        return combined

    try:
        from services.claude_client import (
            send_message_with_usage, is_available,
            get_active_model, calculate_cost_usd, resolve_non_chat_model,
        )
        from repositories.usage_repository import record_usage

        if not is_available():
            return {}

        # Wave 10.A.1 — governance pre-flight. alert_analysis was the only
        # AI surface that bypassed kill switch + budget enforcement (the
        # cron fires every 6h for every org, so unmetered alert AI could
        # quietly drain budget). Now it checks the same guards as chat,
        # digest, and health_explanation. If refused, return empty dict —
        # the engine continues without analysis (zero cost).
        if organization_id:
            try:
                from services.llm.budget_guard import (
                    check_budget_or_raise, GovernanceError,
                )
                await check_budget_or_raise(
                    organization_id=organization_id,
                    feature="alert_analysis",
                    agent_id="alert_analysis",
                )
            except GovernanceError as gov_exc:
                logger.info(
                    "alert_analysis: governance refused (org=%s code=%s): %s",
                    organization_id, gov_exc.error_code, gov_exc,
                )
                return {}

        _model_override = resolve_non_chat_model() or None
        response, usage = await send_message_with_usage(
            system=_build_system_prompt(locale),
            user_message=_build_batch_message(alerts, kpis),
            max_tokens=1500,
            model_version=_model_override,
        )

        # Wave 9.B — record an AIUsageEvent so the call is visible to
        # the governance dashboard. quantity=number of alerts in batch
        # so the per-feature cost reflects the operational reality
        # (1 Anthropic call covered N alerts).
        if organization_id:
            model_version = _model_override or get_active_model()
            cost = calculate_cost_usd(
                tokens_prompt=usage.get("input_tokens"),
                tokens_completion=usage.get("output_tokens"),
                cache_read_tokens=usage.get("cache_read_tokens", 0),
                cache_creation_tokens=usage.get("cache_creation_tokens", 0),
                model_version=model_version,
            )
            try:
                await record_usage(
                    org_id=organization_id,
                    module_key="ai_assistant",
                    feature_key="alert_analysis",
                    quantity=len(alerts),
                    tokens_prompt=usage.get("input_tokens"),
                    tokens_completion=usage.get("output_tokens"),
                    cache_read_tokens=usage.get("cache_read_tokens"),
                    cache_creation_tokens=usage.get("cache_creation_tokens"),
                    # Wave 10.B.6 — surface latency for dashboard SLO panels.
                    latency_ms=usage.get("latency_ms"),
                    provider="anthropic",
                    model_version=model_version,
                    cost_usd=cost,
                    agent_id="alert_analysis",
                )
            except Exception as track_exc:
                logger.warning(
                    "alert_analysis: record_usage failed for org=%s: %s",
                    organization_id, track_exc,
                )

        alert_ids = [a.id for a in alerts]
        return _parse_response(response, alert_ids)
    except Exception as e:
        logger.warning("alert_analysis: AI failed: %s", e)
        return {}
